apiVersion: apps/v1
kind: Deployment
metadata:
  name: openzoo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openzoo-server
  template:
    metadata:
      labels:
        app: openzoo-server
    spec:
      containers:
      - name: openzoo-server
        image: 381492186474.dkr.ecr.us-west-1.amazonaws.com/openzoo-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
